version: '3'
services: 
    web:
        build: web
        ports: 
            - "5000:5000"
        links:
            - mysql
    mysql:
        build: mysql
        ports: 
            - "3306:3306"
        volumes: 
            - ./data:/var/lib/mysql