version: '3'
services: 
    web:
        build: .
        ports: 
            - "5000:5000"
        links:
            - sql
        depends_on: 
            - sql
    mysql:
        build: .
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/docker-entrypoint-initdb.d